### ISSUE TITLE
Cannot open the image picker.

### ISSUE THREAD

**Issue by TrianguloY** [TrianguloY/LightningLauncher#16]
If you try to open the image picker (for example by long tap -> [+] -> icon) the image picker is shown but closed almost immediately with a toast saying 'Cannot pick image'.

This appears to be a permission-related issue, because the check at net.pierrox.lightning_launcher.activities.ImagePicker#onRequestPermissionsResult is the one failing.

In fact, it appears it happens because the app doesn't have external storage permission (used by the image picker as a temporal location) in net.pierrox.lightning_launcher.data.FileUtils#LL_EXT_DIR. Other file operations, like writing to log in scripts, doesn't work either.

Possible solutions: change the location to an internal app-available one, or correctly request the required permission.

**Comment by SnowVolf** [comment]
I tried to fix it.  Now the application does not close and does not crash. Now the camera/gallery opens. But when creating an icon, instead of the selected image, the default icon appears (green Android). 

It is quite difficult to diagnose this now, because almost all try/catch blocks are silenced and devoid of any logs. 

I think this is due to the fact that the system of transmitting any results of work is abominably implemented here. For example: ImagePicker selects a photo and writes a copy of it to a file located in a constant. ImageCropper starts, and instead of passing the file path, it just tries to read the file from the constant path. Which looks strange to say the least

**Comment by SnowVolf** [comment]
My progress is recording on #18
